create schema PLAYCE;

create table CLUSTER
(
	ID BIGINT generated by default as identity not null primary key,
	CREATE_DATE TIMESTAMP default current_timestamp not null,
	CREATE_USER BIGINT default 1,
	DELETE_YN VARCHAR(1) default 'N' not null,
	UPDATE_DATE TIMESTAMP default current_timestamp not null,
	UPDATE_USER BIGINT default 1,
	DESCRIPTION VARCHAR(255),
	NAME VARCHAR(255) not null
);

create table DOMAIN
(
	ID BIGINT generated by default as identity not null primary key,
	CREATE_DATE TIMESTAMP default current_timestamp not null,
	CREATE_USER BIGINT default 1,
	DELETE_YN VARCHAR(1) default 'N' not null,
	UPDATE_DATE TIMESTAMP default current_timestamp not null,
	UPDATE_USER BIGINT default 1,
	DESCRIPTION VARCHAR(255),
	NAME VARCHAR(255) not null,
	CLUSTER_ID BIGINT not null
		constraint FK77LNTNPWGIY25P7MXUMT5J488
			references CLUSTER (ID)
);

create table HOST
(
	ID BIGINT generated by default as identity not null primary key,
	CREATE_DATE TIMESTAMP default current_timestamp not null,
	CREATE_USER BIGINT default 1,
	DELETE_YN VARCHAR(1) default 'N' not null,
	UPDATE_DATE TIMESTAMP default current_timestamp not null,
	UPDATE_USER BIGINT default 1,
	AGENT_INSTALL_PATH VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	IP_ADDRESS VARCHAR(255) not null,
	KEY_FILE_PATH VARCHAR(255),
	KEY_STRING VARCHAR(4096),
	MONITORING_YN VARCHAR(1) default 'Y',
	NAME VARCHAR(255) not null,
	PASSWORD VARCHAR(512),
	PORT INTEGER,
	USERNAME VARCHAR(255),
	SCOUTER_SERVER_ID BIGINT,
	SUDOER_YN VARCHAR(1)
);

create table HOST_DETAIL
(
	ID BIGINT generated by default as identity not null primary key,
	ARCHITECTURE VARCHAR(255),
	CORES INTEGER,
	CPU INTEGER,
	DISK BIGINT,
	DNS VARCHAR(255),
	GATEWAY VARCHAR(255),
	HOSTNAME VARCHAR(255),
	IP_ADDRESS VARCHAR(255),
	KERNEL VARCHAR(255),
	MEMORY BIGINT,
	OS VARCHAR(255),
	SWAP BIGINT,
	VENDOR VARCHAR(255),
	HOST_ID BIGINT not null
		unique
		constraint FKA1W7VOL7383WBWGJYL93RFT7Y
			references HOST (ID)
);

create table HOST_MONITOR
(
	ID BIGINT generated by default as identity not null primary key,
	CPU_AVG DOUBLE not null,
	CPU_MAX DOUBLE not null,
	DISK_READ_AVG BIGINT not null,
	DISK_READ_MAX BIGINT not null,
	DISK_USAGE DOUBLE not null,
	DISK_WRITE_AVG BIGINT not null,
	DISK_WRITE_MAX BIGINT not null,
	MEM_AVG BIGINT not null,
	MEM_MAX BIGINT not null,
	MEM_TOTAL BIGINT not null,
	MEM_USAGE_AVG DOUBLE not null,
	MEM_USAGE_MAX DOUBLE not null,
	MONITOR_DATE TIMESTAMP,
	NET_RX_AVG BIGINT not null,
	NET_RX_MAX BIGINT not null,
	NET_TX_AVG BIGINT not null,
	NET_TX_MAX BIGINT not null,
	TYPE VARCHAR(255) not null,
	HOST_ID BIGINT not null
		constraint FKDRJ1GFBSNSQ2AHE9UUTB6IXMO
			references HOST (ID)
);

create table MEMBER
(
	ID BIGINT generated by default as identity not null primary key,
	CREATE_DATE TIMESTAMP default current_timestamp not null,
	CREATE_USER BIGINT default 1,
	DELETE_YN VARCHAR(1) default 'N' not null,
	UPDATE_DATE TIMESTAMP default current_timestamp not null,
	UPDATE_USER BIGINT default 1,
	BLOCK_YN VARCHAR(1) default 'N' not null,
	DESCRIPTION VARCHAR(255),
	EMAIL VARCHAR(255),
	FAIL_LIMIT_COUNT BIGINT default 0 not null,
	LAST_LOGIN_DATE TIMESTAMP,
	PASSWORD VARCHAR(512) not null,
	USER_ID VARCHAR(255) not null,
	USER_NAME VARCHAR(255),
	VIEW_MODE VARCHAR(255)
);

create table ROLE
(
	ID BIGINT generated by default as identity not null primary key,
	NAME VARCHAR(255) not null unique
);

create table MEMBERS_ROLES_DOMAINS
(
	ID BIGINT generated by default as identity not null primary key,
	DOMAIN_ID BIGINT
		constraint FKH49FUTGKWYPUJOIC27F7L1WS8
			references DOMAIN (ID),
	MEMBER_ID BIGINT
		constraint FKIPTPPWNUSOK0JFXGDKE1GF6YQ
			references MEMBER (ID),
	ROLE_ID BIGINT
		constraint FKFEVFXTD6O29F8NF7SRIQJ8OQS
			references ROLE (ID)
);

create table HISTORY
(
	ID BIGINT generated by default as identity not null primary key,
	ACCESS_CONTROL_ID BIGINT,
	APPLICATION_ID BIGINT,
	ATLASSIAN_SERVER_ID BIGINT,
	CLUSTER_ID BIGINT,
	CODE INTEGER not null,
	CONFIG_FILE VARCHAR(255),
	CREATE_DATE TIMESTAMP default current_timestamp,
	DATASOURCE_ID BIGINT,
	DELETE_YN VARCHAR(1) default 'N' not null,
	DOMAIN_ID BIGINT,
	END_DATE TIMESTAMP default current_timestamp,
	ENGINE_ID BIGINT,
	HOST_ID BIGINT,
	MESSAGE VARCHAR(255),
	PROCESS_UUID VARCHAR(255) not null,
	READ_YN VARCHAR(1) default 'N' not null,
	SCOUTER_SERVER_ID BIGINT,
	SESSION_SERVER_ID BIGINT,
	STATUS_CODE VARCHAR(255) not null,
	TASK_USER BIGINT default 1,
	TITLE VARCHAR(255) not null,
	WEB_APP_SERVER_ID BIGINT,
	WEB_SERVER_ID BIGINT,
	WIZARD_ID BIGINT
);